/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as IndexRouteImport } from './routes/index'

const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/response': typeof ResponseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/response': typeof ResponseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/response': typeof ResponseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hardware' | '/response'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hardware' | '/response'
  id: '__root__' | '/' | '/hardware' | '/response'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareRoute: typeof HardwareRoute
  ResponseRoute: typeof ResponseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareRoute: HardwareRoute,
  ResponseRoute: ResponseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
